import { Product, SearchParams } from '../types/index.js';

const USER_AGENTS = [
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36',
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36',
  'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:123.0) Gecko/20100101 Firefox/123.0',
];

export function randomUserAgent(): string {
  return USER_AGENTS[Math.floor(Math.random() * USER_AGENTS.length)];
}

// ─── Mock Product Catalogue ───────────────────────────────────────────────────

const AMAZON_PRODUCTS: Product[] = [
  {
    id: 'B0CHX3TB6N',
    platform: 'amazon',
    title: 'boAt Rockerz 450 Bluetooth On-Ear Headphones with 15H Battery',
    price: 1299,
    currency: 'INR',
    rating: 4.1,
    reviewCount: 85432,
    imageUrl: 'https://m.media-amazon.com/images/I/61bOPADIsAL._SL1500_.jpg',
    productUrl: 'https://www.amazon.in/dp/B0CHX3TB6N',
    specs: { Brand: 'boAt', Color: 'Black', 'Battery Life': '15 hrs', Connectivity: 'Bluetooth 5.0' },
  },
  {
    id: 'B0CXBY9J4T',
    platform: 'amazon',
    title: 'Sony WH-1000XM5 Wireless Noise Cancelling Headphones',
    price: 22990,
    currency: 'INR',
    rating: 4.5,
    reviewCount: 12840,
    imageUrl: 'https://m.media-amazon.com/images/I/61KJlhpBkpL._SL1500_.jpg',
    productUrl: 'https://www.amazon.in/dp/B0CXBY9J4T',
    specs: { Brand: 'Sony', 'Noise Cancellation': 'Yes', 'Battery Life': '30 hrs', Connectivity: 'Bluetooth 5.2' },
  },
  {
    id: 'B0BVXG2WX3',
    platform: 'amazon',
    title: 'Nike Revolution 6 Running Shoes for Men',
    price: 3695,
    currency: 'INR',
    rating: 4.3,
    reviewCount: 9210,
    imageUrl: 'https://m.media-amazon.com/images/I/71QmPxl2hkL._UY500_.jpg',
    productUrl: 'https://www.amazon.in/dp/B0BVXG2WX3',
    specs: { Brand: 'Nike', Material: 'Mesh', Sole: 'Rubber', 'Fit Type': 'Regular' },
  },
  {
    id: 'B08N5W4NMB',
    platform: 'amazon',
    title: 'OnePlus Nord CE 3 Lite 5G (8GB RAM, 128GB Storage)',
    price: 17999,
    currency: 'INR',
    rating: 4.2,
    reviewCount: 34560,
    imageUrl: 'https://m.media-amazon.com/images/I/71i7xY1FFDL._SL1500_.jpg',
    productUrl: 'https://www.amazon.in/dp/B08N5W4NMB',
    specs: { Brand: 'OnePlus', RAM: '8 GB', Storage: '128 GB', 'Battery': '5000 mAh' },
  },
  {
    id: 'B09X7BKB9D',
    platform: 'amazon',
    title: 'JBL Flip 6 Portable Bluetooth Speaker Waterproof',
    price: 8999,
    currency: 'INR',
    rating: 4.4,
    reviewCount: 21345,
    imageUrl: 'https://m.media-amazon.com/images/I/71GsB2aQa3L._SL1500_.jpg',
    productUrl: 'https://www.amazon.in/dp/B09X7BKB9D',
    specs: { Brand: 'JBL', 'Water Resistance': 'IP67', 'Battery Life': '12 hrs', Connectivity: 'Bluetooth 5.1' },
  },
  {
    id: 'B0BHZTKSQY',
    platform: 'amazon',
    title: 'Adidas Duramo SL Running Shoes Men',
    price: 2999,
    currency: 'INR',
    rating: 4.1,
    reviewCount: 6780,
    imageUrl: 'https://m.media-amazon.com/images/I/71MuoYRVxeL._UY500_.jpg',
    productUrl: 'https://www.amazon.in/dp/B0BHZTKSQY',
    specs: { Brand: 'Adidas', Material: 'Knit upper', Sole: 'Rubber', 'Closure': 'Lace-up' },
  },
  {
    id: 'B0B9V9GKDM',
    platform: 'amazon',
    title: 'Samsung Galaxy F34 5G (6GB RAM, 128GB)',
    price: 14999,
    currency: 'INR',
    rating: 4.2,
    reviewCount: 18920,
    imageUrl: 'https://m.media-amazon.com/images/I/71jbxFCHIfL._SL1500_.jpg',
    productUrl: 'https://www.amazon.in/dp/B0B9V9GKDM',
    specs: { Brand: 'Samsung', RAM: '6 GB', Storage: '128 GB', Battery: '6000 mAh' },
  },
  {
    id: 'B0CH3QJVH9',
    platform: 'amazon',
    title: 'HP 15s Laptop Intel Core i3, 8GB RAM, 512GB SSD',
    price: 39990,
    currency: 'INR',
    rating: 4.3,
    reviewCount: 5670,
    imageUrl: 'https://m.media-amazon.com/images/I/71W1O0xjqtL._SL1500_.jpg',
    productUrl: 'https://www.amazon.in/dp/B0CH3QJVH9',
    specs: { Brand: 'HP', Processor: 'Intel Core i3', RAM: '8 GB', Storage: '512 GB SSD' },
  },
];

const FLIPKART_PRODUCTS: Product[] = [
  {
    id: 'MOBGTAGPTHUZECP2',
    platform: 'flipkart',
    title: 'Realme Narzo N55 (Prime Black, 4GB RAM, 64GB Storage)',
    price: 10999,
    currency: 'INR',
    rating: 4.2,
    reviewCount: 28450,
    imageUrl: 'https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/j/z/b/-original-imagtb3aghkzfhyg.jpeg',
    productUrl: 'https://www.flipkart.com/realme-narzo-n55/p/MOBGTAGPTHUZECP2',
    specs: { Brand: 'Realme', RAM: '4 GB', Storage: '64 GB', Battery: '5000 mAh', MRP: '₹12,999' },
  },
  {
    id: 'WATGPZHMHPYQGSGT',
    platform: 'flipkart',
    title: 'Fastrack Reflex Beat Smartwatch with 1.83" Display',
    price: 1995,
    currency: 'INR',
    rating: 3.9,
    reviewCount: 14230,
    imageUrl: 'https://rukminim2.flixcart.com/image/416/416/xif0q/smartwatch/q/z/h/-original-imaghzqgyytnhrky.jpeg',
    productUrl: 'https://www.flipkart.com/fastrack-reflex-beat/p/WATGPZHMHPYQGSGT',
    specs: { Brand: 'Fastrack', 'Display': '1.83 inch', 'Battery': '7 days', 'Water Resistance': 'IP68', MRP: '₹3,495' },
  },
  {
    id: 'SHOGTDHKH5FQXZPQ',
    platform: 'flipkart',
    title: 'Puma Softride Pro Running Shoes For Men',
    price: 2499,
    currency: 'INR',
    rating: 4.3,
    reviewCount: 8760,
    imageUrl: 'https://rukminim2.flixcart.com/image/416/416/xif0q/shoe/b/f/g/-original-imagtzygyqhgghbg.jpeg',
    productUrl: 'https://www.flipkart.com/puma-softride-pro/p/SHOGTDHKH5FQXZPQ',
    specs: { Brand: 'Puma', Material: 'Mesh', Sole: 'EVA', MRP: '₹4,499', Highlights: 'Lightweight, Breathable' },
  },
  {
    id: 'TVSGPZV3FHYMDQZM',
    platform: 'flipkart',
    title: 'MI 32 inch HD Ready Smart LED TV (2023)',
    price: 12499,
    currency: 'INR',
    rating: 4.3,
    reviewCount: 45320,
    imageUrl: 'https://rukminim2.flixcart.com/image/416/416/xif0q/television/q/8/a/-original-imagpge7nhz8qhre.jpeg',
    productUrl: 'https://www.flipkart.com/mi-80cm-32-inches-hd-ready-smart-led-tv/p/TVSGPZV3FHYMDQZM',
    specs: { Brand: 'MI', 'Screen Size': '32 inch', Resolution: 'HD Ready', 'Smart TV': 'Yes', MRP: '₹17,999' },
  },
  {
    id: 'TABGTAJVKFZFNHQZ',
    platform: 'flipkart',
    title: 'Lenovo IdeaPad Slim 3 Intel Core i5, 8GB RAM, 512GB SSD',
    price: 42990,
    currency: 'INR',
    rating: 4.4,
    reviewCount: 7890,
    imageUrl: 'https://rukminim2.flixcart.com/image/416/416/xif0q/computer/w/b/o/-original-imagpyygrghzhhqz.jpeg',
    productUrl: 'https://www.flipkart.com/lenovo-ideapad-slim-3/p/TABGTAJVKFZFNHQZ',
    specs: { Brand: 'Lenovo', Processor: 'Intel Core i5', RAM: '8 GB', Storage: '512 GB SSD', MRP: '₹52,990' },
  },
  {
    id: 'EARGTAB3ZMHQDMZP',
    platform: 'flipkart',
    title: 'boAt Airdopes 141 TWS Earbuds 42H Playtime',
    price: 999,
    currency: 'INR',
    rating: 4.1,
    reviewCount: 112340,
    imageUrl: 'https://rukminim2.flixcart.com/image/416/416/xif0q/headphone/w/3/w/-original-imaghdgfhzqmxqhf.jpeg',
    productUrl: 'https://www.flipkart.com/boat-airdopes-141/p/EARGTAB3ZMHQDMZP',
    specs: { Brand: 'boAt', 'Total Playtime': '42 hrs', 'Water Resistance': 'IPX4', MRP: '₹2,990', Connectivity: 'Bluetooth 5.3' },
  },
  {
    id: 'MOBGTAKUZHYFQMPZ',
    platform: 'flipkart',
    title: 'Motorola G84 5G (256GB, Viva Magenta)',
    price: 15999,
    currency: 'INR',
    rating: 4.3,
    reviewCount: 9870,
    imageUrl: 'https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/4/b/h/-original-imagqhbzpyzfhfcv.jpeg',
    productUrl: 'https://www.flipkart.com/moto-g84-5g/p/MOBGTAKUZHYFQMPZ',
    specs: { Brand: 'Motorola', RAM: '12 GB', Storage: '256 GB', Battery: '5000 mAh', MRP: '₹19,999' },
  },
  {
    id: 'SHOGTAB4UMHQZPLT',
    platform: 'flipkart',
    title: 'Skechers Go Walk Flex Men Casual Shoes',
    price: 3199,
    currency: 'INR',
    rating: 4.4,
    reviewCount: 5620,
    imageUrl: 'https://rukminim2.flixcart.com/image/416/416/xif0q/shoe/m/y/p/-original-imagpyzghhfqzmpz.jpeg',
    productUrl: 'https://www.flipkart.com/skechers-go-walk-flex/p/SHOGTAB4UMHQZPLT',
    specs: { Brand: 'Skechers', Material: 'Mesh', Sole: 'Rubber', MRP: '₹5,499', Highlights: 'Memory Foam, Air-Cooled' },
  },
];

const MYNTRA_PRODUCTS: Product[] = [
  {
    id: '24228878',
    platform: 'myntra',
    title: 'Nike Men Revolution 6 Running Shoes',
    price: 3695,
    currency: 'INR',
    rating: 4.3,
    reviewCount: 4320,
    imageUrl: 'https://assets.myntassets.com/h_560,q_90,w_420/v1/assets/images/24228878/2023/8/21/abc.jpg',
    productUrl: 'https://www.myntra.com/sports-shoes/nike/nike-men-revolution-6-running-shoes/24228878/buy',
    specs: { Brand: 'Nike', Gender: 'Men', Category: 'Sports Shoes', MRP: '₹4,595' },
  },
  {
    id: '20457322',
    platform: 'myntra',
    title: "Levi's Men Slim Fit Stretchable Jeans",
    price: 1919,
    currency: 'INR',
    rating: 4.2,
    reviewCount: 8760,
    imageUrl: 'https://assets.myntassets.com/h_560,q_90,w_420/v1/assets/images/20457322/2022/abc.jpg',
    productUrl: 'https://www.myntra.com/jeans/levis/levis-men-slim-fit-stretchable-jeans/20457322/buy',
    specs: { Brand: "Levi's", Gender: 'Men', Category: 'Jeans', MRP: '₹3,999', Fit: 'Slim' },
  },
  {
    id: '25671234',
    platform: 'myntra',
    title: 'Puma Men Sneaker Running Shoes',
    price: 3149,
    currency: 'INR',
    rating: 4.4,
    reviewCount: 6540,
    imageUrl: 'https://assets.myntassets.com/h_560,q_90,w_420/v1/assets/images/25671234/2023/abc.jpg',
    productUrl: 'https://www.myntra.com/sports-shoes/puma/puma-men-sneaker/25671234/buy',
    specs: { Brand: 'Puma', Gender: 'Men', Category: 'Sports Shoes', MRP: '₹5,999' },
  },
  {
    id: '18934567',
    platform: 'myntra',
    title: 'H&M Women Oversized Cotton T-Shirt',
    price: 799,
    currency: 'INR',
    rating: 4.1,
    reviewCount: 12340,
    imageUrl: 'https://assets.myntassets.com/h_560,q_90,w_420/v1/assets/images/18934567/2023/abc.jpg',
    productUrl: 'https://www.myntra.com/tshirts/hm/hm-women-oversized-tshirt/18934567/buy',
    specs: { Brand: 'H&M', Gender: 'Women', Category: 'T-Shirts', MRP: '₹999', Material: 'Cotton' },
  },
  {
    id: '22345678',
    platform: 'myntra',
    title: 'Adidas Men Ultraboost Light Running Shoes',
    price: 14999,
    currency: 'INR',
    rating: 4.5,
    reviewCount: 3210,
    imageUrl: 'https://assets.myntassets.com/h_560,q_90,w_420/v1/assets/images/22345678/2023/abc.jpg',
    productUrl: 'https://www.myntra.com/sports-shoes/adidas/adidas-men-ultraboost/22345678/buy',
    specs: { Brand: 'Adidas', Gender: 'Men', Category: 'Sports Shoes', MRP: '₹19,999', Technology: 'Boost Cushioning' },
  },
  {
    id: '19876543',
    platform: 'myntra',
    title: 'Roadster Men Solid Hooded Sweatshirt',
    price: 629,
    currency: 'INR',
    rating: 4.0,
    reviewCount: 23450,
    imageUrl: 'https://assets.myntassets.com/h_560,q_90,w_420/v1/assets/images/19876543/2023/abc.jpg',
    productUrl: 'https://www.myntra.com/sweatshirts/roadster/roadster-men-sweatshirt/19876543/buy',
    specs: { Brand: 'Roadster', Gender: 'Men', Category: 'Sweatshirts', MRP: '₹1,299', Material: 'Cotton Blend' },
  },
  {
    id: '17654321',
    platform: 'myntra',
    title: 'ONLY Women Flared Fit Midi Dress',
    price: 1349,
    currency: 'INR',
    rating: 4.2,
    reviewCount: 7890,
    imageUrl: 'https://assets.myntassets.com/h_560,q_90,w_420/v1/assets/images/17654321/2023/abc.jpg',
    productUrl: 'https://www.myntra.com/dresses/only/only-women-midi-dress/17654321/buy',
    specs: { Brand: 'ONLY', Gender: 'Women', Category: 'Dresses', MRP: '₹2,299', Length: 'Midi' },
  },
  {
    id: '21098765',
    platform: 'myntra',
    title: 'U.S. Polo Assn. Men Slim Fit Casual Shirt',
    price: 1079,
    currency: 'INR',
    rating: 4.3,
    reviewCount: 9870,
    imageUrl: 'https://assets.myntassets.com/h_560,q_90,w_420/v1/assets/images/21098765/2023/abc.jpg',
    productUrl: 'https://www.myntra.com/shirts/us-polo-assn/us-polo-assn-men-shirt/21098765/buy',
    specs: { Brand: 'U.S. Polo Assn.', Gender: 'Men', Category: 'Shirts', MRP: '₹1,999', Fit: 'Slim' },
  },
];

const MEESHO_PRODUCTS: Product[] = [
  {
    id: '629872341',
    platform: 'meesho',
    title: 'DKGD Men Slim Fit Casual Shirt Pack of 3',
    price: 399,
    currency: 'INR',
    rating: 3.9,
    reviewCount: 24560,
    imageUrl: 'https://images.meesho.com/images/products/629872341/u6mex_512.webp',
    productUrl: 'https://www.meesho.com/dkgd-men-slim-fit-shirts/p/629872341',
    specs: { Brand: 'DKGD', Category: 'Shirts', MRP: '₹799', Material: 'Cotton Blend' },
  },
  {
    id: '445213987',
    platform: 'meesho',
    title: 'Clovia Women Padded Non-Wired Full Coverage Bra Set',
    price: 329,
    currency: 'INR',
    rating: 4.1,
    reviewCount: 38900,
    imageUrl: 'https://images.meesho.com/images/products/445213987/tbqhm_512.webp',
    productUrl: 'https://www.meesho.com/clovia-bra-set/p/445213987',
    specs: { Brand: 'Clovia', Category: 'Lingerie', MRP: '₹699' },
  },
  {
    id: '782341256',
    platform: 'meesho',
    title: 'WearMe Women Floral Print Rayon Kurti',
    price: 279,
    currency: 'INR',
    rating: 4.0,
    reviewCount: 54320,
    imageUrl: 'https://images.meesho.com/images/products/782341256/abc_512.webp',
    productUrl: 'https://www.meesho.com/wearme-kurti/p/782341256',
    specs: { Brand: 'WearMe', Category: 'Kurtis', MRP: '₹599', Material: 'Rayon' },
  },
  {
    id: '312987456',
    platform: 'meesho',
    title: 'boAt Bassheads 100 Wired Earphones with Mic',
    price: 349,
    currency: 'INR',
    rating: 4.0,
    reviewCount: 89430,
    imageUrl: 'https://images.meesho.com/images/products/312987456/abc_512.webp',
    productUrl: 'https://www.meesho.com/boat-bassheads-100/p/312987456',
    specs: { Brand: 'boAt', Category: 'Earphones', MRP: '₹699', Connectivity: 'Wired' },
  },
  {
    id: '556789123',
    platform: 'meesho',
    title: 'GUSTO Home Decor Curtain Set of 2 (5 Feet)',
    price: 449,
    currency: 'INR',
    rating: 3.8,
    reviewCount: 16780,
    imageUrl: 'https://images.meesho.com/images/products/556789123/abc_512.webp',
    productUrl: 'https://www.meesho.com/gusto-curtains/p/556789123',
    specs: { Brand: 'GUSTO', Category: 'Home Decor', MRP: '₹999', Material: 'Polyester' },
  },
  {
    id: '891234567',
    platform: 'meesho',
    title: 'Fastrack Reflex 3.0 Fitness Smartband',
    price: 1299,
    currency: 'INR',
    rating: 4.0,
    reviewCount: 22100,
    imageUrl: 'https://images.meesho.com/images/products/891234567/abc_512.webp',
    productUrl: 'https://www.meesho.com/fastrack-reflex-3/p/891234567',
    specs: { Brand: 'Fastrack', Category: 'Fitness Band', MRP: '₹2,495', 'Water Resistance': 'IP67' },
  },
  {
    id: '234567891',
    platform: 'meesho',
    title: 'Trendia Women Ethnic Printed Saree with Blouse',
    price: 499,
    currency: 'INR',
    rating: 3.9,
    reviewCount: 31450,
    imageUrl: 'https://images.meesho.com/images/products/234567891/abc_512.webp',
    productUrl: 'https://www.meesho.com/trendia-saree/p/234567891',
    specs: { Brand: 'Trendia', Category: 'Sarees', MRP: '₹1,299', Material: 'Art Silk' },
  },
  {
    id: '678912345',
    platform: 'meesho',
    title: 'Wildcraft Unisex 30L Polyester Backpack',
    price: 899,
    currency: 'INR',
    rating: 4.1,
    reviewCount: 9870,
    imageUrl: 'https://images.meesho.com/images/products/678912345/abc_512.webp',
    productUrl: 'https://www.meesho.com/wildcraft-backpack/p/678912345',
    specs: { Brand: 'Wildcraft', Category: 'Bags', MRP: '₹1,799', Capacity: '30L' },
  },
];

const NYKAA_PRODUCTS: Product[] = [
  {
    id: '7610923',
    platform: 'nykaa',
    title: "Minimalist 2% Salicylic Acid Face Serum for Acne & Blackheads",
    price: 599,
    currency: 'INR',
    rating: 4.4,
    reviewCount: 43210,
    imageUrl: 'https://adn-static1.nykaa.com/nykdesignstudio-images/pub/media/catalog/product/m/i/minimalist-serum.jpg',
    productUrl: 'https://www.nykaa.com/minimalist-salicylic-acid-serum/p/7610923',
    specs: { Brand: 'Minimalist', Category: 'Serum', MRP: '₹799', 'Key Ingredient': 'Salicylic Acid 2%' },
  },
  {
    id: '3421890',
    platform: 'nykaa',
    title: 'Lakme Eyeconic Kajal Twin Pack — Deep Black',
    price: 374,
    currency: 'INR',
    rating: 4.3,
    reviewCount: 78900,
    imageUrl: 'https://adn-static1.nykaa.com/nykdesignstudio-images/pub/media/catalog/product/l/a/lakme-kajal.jpg',
    productUrl: 'https://www.nykaa.com/lakme-eyeconic-kajal-twin/p/3421890',
    specs: { Brand: 'Lakme', Category: 'Eye Makeup', MRP: '₹449', 'Duration': 'Long Lasting' },
  },
  {
    id: '8923401',
    platform: 'nykaa',
    title: 'The Ordinary Hyaluronic Acid 2% + B5 Face Serum 30ml',
    price: 899,
    currency: 'INR',
    rating: 4.5,
    reviewCount: 34560,
    imageUrl: 'https://adn-static1.nykaa.com/nykdesignstudio-images/pub/media/catalog/product/t/h/the-ordinary-ha.jpg',
    productUrl: 'https://www.nykaa.com/the-ordinary-ha-serum/p/8923401',
    specs: { Brand: 'The Ordinary', Category: 'Serum', MRP: '₹1,100', 'Key Ingredient': 'Hyaluronic Acid 2%' },
  },
  {
    id: '5671234',
    platform: 'nykaa',
    title: 'Mamaearth Onion Hair Oil for Hair Fall Control 250ml',
    price: 347,
    currency: 'INR',
    rating: 4.2,
    reviewCount: 62340,
    imageUrl: 'https://adn-static1.nykaa.com/nykdesignstudio-images/pub/media/catalog/product/m/a/mamaearth-onion-oil.jpg',
    productUrl: 'https://www.nykaa.com/mamaearth-onion-oil/p/5671234',
    specs: { Brand: 'Mamaearth', Category: 'Hair Oil', MRP: '₹499', 'Volume': '250ml' },
  },
  {
    id: '2345678',
    platform: 'nykaa',
    title: "Nykaa SKINRX 10% Vitamin C Brightening Serum 30ml",
    price: 449,
    currency: 'INR',
    rating: 4.1,
    reviewCount: 18900,
    imageUrl: 'https://adn-static1.nykaa.com/nykdesignstudio-images/pub/media/catalog/product/n/y/nykaa-vitc-serum.jpg',
    productUrl: 'https://www.nykaa.com/nykaa-skinrx-vitamin-c-serum/p/2345678',
    specs: { Brand: 'Nykaa', Category: 'Serum', MRP: '₹699', 'Key Ingredient': 'Vitamin C 10%' },
  },
  {
    id: '9876541',
    platform: 'nykaa',
    title: 'Biotique Bio Papaya Revitalizing Tan Removal Scrub 235g',
    price: 199,
    currency: 'INR',
    rating: 4.0,
    reviewCount: 29870,
    imageUrl: 'https://adn-static1.nykaa.com/nykdesignstudio-images/pub/media/catalog/product/b/i/biotique-scrub.jpg',
    productUrl: 'https://www.nykaa.com/biotique-papaya-scrub/p/9876541',
    specs: { Brand: 'Biotique', Category: 'Face Scrub', MRP: '₹275', 'Weight': '235g' },
  },
  {
    id: '6543219',
    platform: 'nykaa',
    title: 'L\'Oreal Paris Elvive Extraordinary Oil Shampoo 640ml',
    price: 499,
    currency: 'INR',
    rating: 4.2,
    reviewCount: 41230,
    imageUrl: 'https://adn-static1.nykaa.com/nykdesignstudio-images/pub/media/catalog/product/l/o/loreal-shampoo.jpg',
    productUrl: 'https://www.nykaa.com/loreal-elvive-shampoo/p/6543219',
    specs: { Brand: "L'Oreal Paris", Category: 'Shampoo', MRP: '₹699', 'Volume': '640ml' },
  },
  {
    id: '3214567',
    platform: 'nykaa',
    title: 'Maybelline Fit Me Matte+Poreless Foundation SPF22',
    price: 499,
    currency: 'INR',
    rating: 4.3,
    reviewCount: 55670,
    imageUrl: 'https://adn-static1.nykaa.com/nykdesignstudio-images/pub/media/catalog/product/m/a/maybelline-fitme.jpg',
    productUrl: 'https://www.nykaa.com/maybelline-fit-me-foundation/p/3214567',
    specs: { Brand: 'Maybelline', Category: 'Foundation', MRP: '₹675', 'SPF': '22' },
  },
];

const AJIO_PRODUCTS: Product[] = [
  {
    id: '469235421',
    platform: 'ajio',
    title: 'Wrangler Men Regular Fit Stretch Jeans',
    price: 1799,
    currency: 'INR',
    rating: 4.2,
    reviewCount: 12340,
    imageUrl: 'https://assets.ajio.com/medias/sys_master/root/20231011/wrangler-jeans.jpg',
    productUrl: 'https://www.ajio.com/wrangler-men-regular-fit-jeans/p/469235421',
    specs: { Brand: 'Wrangler', Category: 'Jeans', MRP: '₹3,299', Fit: 'Regular' },
  },
  {
    id: '890123456',
    platform: 'ajio',
    title: 'Allen Solly Men Slim Fit Formal Shirt',
    price: 1019,
    currency: 'INR',
    rating: 4.3,
    reviewCount: 8760,
    imageUrl: 'https://assets.ajio.com/medias/sys_master/root/20231011/allensolly-shirt.jpg',
    productUrl: 'https://www.ajio.com/allen-solly-slim-fit-shirt/p/890123456',
    specs: { Brand: 'Allen Solly', Category: 'Formal Shirts', MRP: '₹1,799', Fit: 'Slim' },
  },
  {
    id: '567891234',
    platform: 'ajio',
    title: 'ONLY Women Slim Fit High-Rise Jeans',
    price: 1499,
    currency: 'INR',
    rating: 4.1,
    reviewCount: 9870,
    imageUrl: 'https://assets.ajio.com/medias/sys_master/root/20231011/only-jeans.jpg',
    productUrl: 'https://www.ajio.com/only-women-high-rise-jeans/p/567891234',
    specs: { Brand: 'ONLY', Category: 'Jeans', MRP: '₹2,999', Fit: 'Slim', Rise: 'High' },
  },
  {
    id: '234567890',
    platform: 'ajio',
    title: 'Ajio Men Relaxed Fit Jogger Pants',
    price: 699,
    currency: 'INR',
    rating: 4.0,
    reviewCount: 23450,
    imageUrl: 'https://assets.ajio.com/medias/sys_master/root/20231011/ajio-jogger.jpg',
    productUrl: 'https://www.ajio.com/ajio-men-jogger/p/234567890',
    specs: { Brand: 'Ajio', Category: 'Joggers', MRP: '₹1,299', Fit: 'Relaxed', Material: 'Cotton Blend' },
  },
  {
    id: '901234567',
    platform: 'ajio',
    title: 'Reebok Men Training Colorblock T-Shirt',
    price: 899,
    currency: 'INR',
    rating: 4.2,
    reviewCount: 7890,
    imageUrl: 'https://assets.ajio.com/medias/sys_master/root/20231011/reebok-tshirt.jpg',
    productUrl: 'https://www.ajio.com/reebok-men-training-tshirt/p/901234567',
    specs: { Brand: 'Reebok', Category: 'T-Shirts', MRP: '₹1,899', Material: 'Polyester' },
  },
  {
    id: '678901234',
    platform: 'ajio',
    title: 'Van Heusen Women Straight Kurta with Palazzo Set',
    price: 1799,
    currency: 'INR',
    rating: 4.3,
    reviewCount: 5640,
    imageUrl: 'https://assets.ajio.com/medias/sys_master/root/20231011/vanheusen-kurta.jpg',
    productUrl: 'https://www.ajio.com/van-heusen-kurta-palazzo/p/678901234',
    specs: { Brand: 'Van Heusen', Category: 'Ethnic Sets', MRP: '₹3,499', Fit: 'Straight' },
  },
  {
    id: '345678901',
    platform: 'ajio',
    title: 'Levis Men 511 Slim Fit Mid-Rise Jeans',
    price: 2099,
    currency: 'INR',
    rating: 4.4,
    reviewCount: 19870,
    imageUrl: 'https://assets.ajio.com/medias/sys_master/root/20231011/levis-511-jeans.jpg',
    productUrl: 'https://www.ajio.com/levis-511-slim-jeans/p/345678901',
    specs: { Brand: "Levi's", Category: 'Jeans', MRP: '₹3,999', Fit: 'Slim', Rise: 'Mid' },
  },
  {
    id: '123456789',
    platform: 'ajio',
    title: 'Nike Men Sportswear Swoosh Hoodie',
    price: 3499,
    currency: 'INR',
    rating: 4.5,
    reviewCount: 6780,
    imageUrl: 'https://assets.ajio.com/medias/sys_master/root/20231011/nike-hoodie.jpg',
    productUrl: 'https://www.ajio.com/nike-sportswear-swoosh-hoodie/p/123456789',
    specs: { Brand: 'Nike', Category: 'Hoodies', MRP: '₹5,995', Material: 'Fleece' },
  },
];

const ALL_PRODUCTS: Record<string, Product[]> = {
  amazon: AMAZON_PRODUCTS,
  flipkart: FLIPKART_PRODUCTS,
  myntra: MYNTRA_PRODUCTS,
  meesho: MEESHO_PRODUCTS,
  nykaa: NYKAA_PRODUCTS,
  ajio: AJIO_PRODUCTS,
};

// ─── Exported helpers ─────────────────────────────────────────────────────────

export function getMockProducts(
  platform: string,
  query: string,
  params: Partial<SearchParams>
): Product[] {
  const catalogue = ALL_PRODUCTS[platform] ?? [];
  const keywords = query.toLowerCase().split(/\s+/);

  let results = catalogue.filter((p) => {
    const searchable = `${p.title} ${p.specs['Brand'] ?? ''} ${p.specs['Category'] ?? ''}`.toLowerCase();
    return keywords.some((kw) => searchable.includes(kw));
  });

  // If no keyword match, return all (generic fallback)
  if (results.length === 0) results = catalogue;

  if (params.minPrice !== undefined) results = results.filter((p) => p.price >= params.minPrice!);
  if (params.maxPrice !== undefined) results = results.filter((p) => p.price <= params.maxPrice!);

  return results.sort((a, b) => b.rating - a.rating).slice(0, 5);
}

export function getMockProduct(platform: string, id: string): Product | null {
  return ALL_PRODUCTS[platform]?.find((p) => p.id === id) ?? null;
}
